### ISSUE TITLE
No package release on GitHub

### ISSUE THREAD

**Issue by androidacy-user** [av01d/fontpicker-jquery-plugin#14]
[This package](https://www.jsdelivr.com/package/gh/av01d/fontpicker-jquery-plugin) doesn't have any [GitHub release](https://help.github.com/articles/about-releases/). Could you please create one, so that people can use this project from jsDelivr CDN?

**Comment by av01d** [comment]
Your wish is my command. Release available now.
https://github.com/av01d/fontpicker-jquery-plugin/releases/tag/1.4.3
