### ISSUE TITLE
allow also ttf as local fonts only not just woff

### ISSUE THREAD

**Issue by gpetrov** [av01d/fontpicker-jquery-plugin#16]
currently the list of local files have hardcoded the woff extension onloading. See https://github.com/av01d/fontpicker-jquery-plugin/blob/master/dist/jquery.fontpicker.js#L5400

but this is not always desired, sometimes we just need to show ttf fonts list and load the ttf files in the browser.

also all browsers these days support ttf just fine, so loading shouldn't be a problem.

https://caniuse.com/ttf

Could you implement that as option?

**Comment by av01d** [comment]
What do you propose? An option to set the font file extension (either `woff` or `ttf`)?
```
$('#font3').fontpicker({
  localFontsUrl: 'fonts/',
  localFontsType: 'ttf', // Either 'woff' or 'ttf'
  localFonts: {.....}
})
```

Or....?

**Comment by gpetrov** [comment]
Exactly that will be great! Just a config option that defaults indeed to woff extensions but can be changed to others.

**Comment by av01d** [comment]
Your wish is my command. The `localFontsType` configuration parameter has been added in version 1.5.
