### ISSUE TITLE
getFavorites error

### ISSUE THREAD

**Issue by Ed-Dikotope** [av01d/fontpicker-jquery-plugin#3]
Hi. Thanks for the plugin. Whilst implementing I noticed the following error in the console: Uncaught TypeError: Cannot read property 'undefined' of undefined. Full error:

```
Uncaught TypeError: Cannot read property 'undefined' of undefined
    at Fontpicker.getFavorites (jquery.fontpicker.js?v6:5688)
    at Fontpicker.toggleModal (jquery.fontpicker.js?v6:5499)
    at HTMLDivElement.<anonymous> (jquery.fontpicker.js?v6:5716)
    at HTMLDivElement.dispatch (jquery-3.4.1.min.js:2)
    at HTMLDivElement.v.handle (jquery-3.4.1.min.js:2)
```

**Comment by av01d** [comment]
Seems to be something with the cookie that stores your favorite fonts. But I can't reproduce it (yet).
Please delete your cookies and try again. If you can reproduce the problem, please let me know what steps you take. Thanks!

**Comment by Ed-Dikotope** [comment]
Thanks for the response. It was an undefined value stored in the cookie. I removed the cookie then refreshed and the issue never came back. I think at times when the plugin initializes it may insert undefined in the cookie causing the issue. My cookie value looked like this `favs%7Cundefined%3Aundefined`.

**Comment by av01d** [comment]
Well... the plugin has been in use on many high-traffic sites for quite some time now, and I've never heard about this issue before. If you manage to reproduce the issue, please let me know how, so I can properly fix it.
Thanks for your feedback!
