### ISSUE TITLE
font spec request

### ISSUE THREAD

**Issue by Ed-Dikotope** [av01d/fontpicker-jquery-plugin#4]
Dug into the plugin a bit more. It is really awesome. Saved me few hours just when I was about to write my own. Much appreciated.

I wanted to request, as a part of the font spec, that the font "type", local or google, be returned as a part of the change callback on the input. I have a use case where the type is important, but noticed in the spec that only `family:weight:style` are being returned. Maybe a method to return an object of the selected font somehow that can be consumed? Instead of just setting the input value.

Thanks for looking into this.

**Comment by av01d** [comment]
That's a good idea! I'm already working on it. Expect a new release today.

**Comment by av01d** [comment]
And... it's done. Version 1.0 features an `onSelect` callback that you can use to find out whether a local or Google font was selected. Use this instead of `on('change', ...)`.
