### ISSUE TITLE
How to clear selected font?

### ISSUE THREAD

**Issue by shgohh** [av01d/fontpicker-jquery-plugin#5]
After font is selected, how to clear selected font?

**Comment by av01d** [comment]
Good question. Is a a "Clear" button in the modal sufficient? I'd make it an config-option, something like `showClear: true`. Would that work for you?

**Comment by av01d** [comment]
Version 1.1 implements a `showClear` option, which allows users to clear a selected font.

**Comment by Sumi-Khan** [comment]
When I try the showClear: true, I am unable to see the "Clear" button, additionally the scroll in the modal window disappears.

**Comment by av01d** [comment]
Since version 1.2 (released today), you can use this to programmatically clear a selecterd font:
```
$('#font').val('').trigger('change')
```

**Comment by av01d** [comment]
> When I try the showClear: true, I am unable to see the "Clear" button, additionally the scroll in the modal window disappears.

I cannot reproduce this... but you were probably using IE11? IE11 support is now available, since version 1.2.
