### ISSUE TITLE
Modal not opening in IE

### ISSUE THREAD

**Issue by Sumi-Khan** [av01d/fontpicker-jquery-plugin#6]
Amazing plugin! 
However, the modal for "select a font" is working on other browsers but it is not opening in IE. I have IE11 installed.
Also a suggestion, in addition to favorites, it would be nice for a cookie to store the font and change the site font when the user revisits according to the last user picked font.

**Comment by av01d** [comment]
I've just added IE11 support in version 1.2. Please try!

**Comment by Sumi-Khan** [comment]
Thank you so much. It's working now.
