### ISSUE TITLE
Question: Is it possible to add new fonts dynamically after the page is loaded?

### ISSUE THREAD

**Issue by Nanosplitter** [av01d/fontpicker-jquery-plugin#9]
I am working on a tool where users would be able to upload a font file with a file input. I have working code to load that font into the browser, but I would like to be able to put that font into the font picker while the user is on the page. I would use the name of the file as the font name. I can't find a good way to add font options to the picker after the picker is loaded the first time. I've tried destroying the picker, adding the font to the localFonts list, then recreating it, but it seems to stay destroyed after I destroy it the first time with $('#font').fontpicker('destroy');

**Comment by Nanosplitter** [comment]
I found a sort-of solution. At the end of jquery.fontpicker.js where you have:

![image](https://user-images.githubusercontent.com/22625481/104764122-efeaf200-5734-11eb-823b-f27ffa9f6aa1.png)

I changed it to:

![image](https://user-images.githubusercontent.com/22625481/104764161-fe390e00-5734-11eb-9682-1f2c13e64f9d.png)

This lets me call `jQuery('#font').fontpicker('destroy');` then add the font names I want to add to the localFonts option by doing:
![image](https://user-images.githubusercontent.com/22625481/104764309-32acca00-5735-11eb-8800-c83716d72f2c.png)

Once I do all of that, it lets me start with a fontpicker that looks like this:
![image](https://user-images.githubusercontent.com/22625481/104764381-540db600-5735-11eb-95b4-e7fa7727c6ac.png)

I can upload a font file with a file input, click "add font" that triggers the uploading of the font data to the browser, the destruction of the fontpicker, then the recreation of the fontpicker with the font file name in the localFonts option. Without refreshing the page the fontpicker turns into this:

![image](https://user-images.githubusercontent.com/22625481/104764650-b1096c00-5735-11eb-8f98-959046af8553.png)

I figured I should document this process so if someone in the future wants to do something similar they have a guide!

**Comment by steffenu** [comment]
> I am working on a tool where users would be able to upload a font file with a file input. I have working code to load that font into the browser, but I would like to be able to put that font into the font picker while the user is on the page. I would use the name of the file as the font name. I can't find a good way to add font options to the picker after the picker is loaded the first time. I've tried destroying the picker, adding the font to the localFonts list, then recreating it, but it seems to stay destroyed after I destroy it the first time with $('#font').fontpicker('destroy');

Thanks man. Im actually trying to add Adobe fonts support and upload font support. This was helpful thank you.

**Comment by Nanosplitter** [comment]
> Thanks man. Im actually trying to add Adobe fonts support and upload font support. This was helpful thank you.

No problem! Glad the extra time I spent almost a year ago to document this actually paid off for someone :D
